-- Ab Initio to BigQuery Conversion
-- Graph Name: IODSCoInsuranceProcess_1
-- Generated by: Data Engineer AI Agent
-- Version: 1

-- UDFs required for this script:
-- CREATE OR REPLACE FUNCTION edw_pub.FN_REPLACE_NULL_WITH_SPACES(input_str STRING) RETURNS STRING AS (
--   COALESCE(input_str, ' ')
-- );
-- CREATE OR REPLACE FUNCTION edw_pub.FN_GET_PROCESS_DT(input_dt DATE) RETURNS DATE AS (
--   -- Example logic, actual logic would be in the XFR file
--   input_dt
-- );

CREATE OR REPLACE TABLE work.coin_ins_process_stg1 AS
WITH
-- CTE 1: Source data from IODS_COIN_INS_ASSCN
-- Corresponds to Ab Initio Input Table: IN_TABLE_1 and Reformat: REFORMAT_1
source_iods_coin_ins_asscn AS (
  SELECT
    ins_asscn_key,
    coin_cd,
    eff_start_dt,
    eff_end_dt,
    -- Assuming other columns exist
    'some_other_column' AS some_other_column
  FROM
    edw_pub.iods_coin_ins_asscn
  WHERE
    eff_end_dt > CURRENT_DATE()
),

-- CTE 2: Source data from IODS_COIN_AGNT_ASSCN
-- Corresponds to Ab Initio Input Table: IN_TABLE_2
source_iods_coin_agnt_asscn AS (
  SELECT
    ins_asscn_key,
    agnt_id,
    agnt_role,
    -- Assuming other columns exist
    'another_column' AS another_column
  FROM
    edw_pub.iods_coin_agnt_asscn
),

-- CTE 3: Join the two sources
-- Corresponds to Ab Initio Join component: JOIN_1
joined_data AS (
  SELECT
    a.ins_asscn_key,
    a.coin_cd,
    a.eff_start_dt,
    a.eff_end_dt,
    b.agnt_id,
    b.agnt_role,
    a.some_other_column,
    b.another_column
  FROM
    source_iods_coin_ins_asscn AS a
  INNER JOIN
    source_iods_coin_agnt_asscn AS b
    ON a.ins_asscn_key = b.ins_asscn_key
),

-- CTE 4: Final Reformat and Transformation
-- Corresponds to Ab Initio Reformat component: REFORMAT_2
-- The SORT component is handled by the ORDER BY clause in the final SELECT.
final_reformat AS (
  SELECT
    ins_asscn_key,
    edw_pub.FN_REPLACE_NULL_WITH_SPACES(coin_cd) AS coin_cd,
    edw_pub.FN_GET_PROCESS_DT(eff_start_dt) AS process_start_dt,
    eff_end_dt,
    agnt_id,
    agnt_role,
    some_other_column,
    another_column
  FROM
    joined_data
)

-- Final SELECT to insert into the target table
SELECT
  *
FROM
  final_reformat
ORDER BY
  ins_asscn_key;